let eventsData = [
    {
        id: 0,
        title: "Robowars",
        imgname: "robowars.png",
        brief: "Brace yourself, for the warrior within is set to align with the brute outside. For the flames of war...",
        description: "Brace yourself, for the warrior within is set to align with the brute outside. For the flames of war will hit a fair equinox with the realm of robotics, as the month of February dawns. The extravaganza of technology has supercharged the element of awe.The ultimate Showdown, RoboWars is here with a new category of 15kg, with the original 30 kg and 60 kg bot categories.",
        venue: "VJTI Quad",
        date: "TBD",
        price: "Rs. 3,10,000",
        coordinator1: 'Jay',
        coordinator2: 'Parina',
        contact1: '+91 8928780890',
        contact2: '+91 7400398391',
    },
    {
        id: 1,
        title: "VRC",
        imgname: "vrc.png",
        brief: "VRC stands for VJTI Robotics Challenge, one of the very popular and respected competitions conducted...",
        description: "VRC stands for VJTI Robotics Challenge, one of the very popular and respected competitions conducted by VJTI Technovanza. VRC 10.0 is based on the theme of guardians of the Mumbai City, which aims to applaud the valiant efforts of our brave police officers on the eve of the dreadful attacks of 26/11.",
        venue: "Outside CCF",
        date: "TBD",
        price: "Rs. 80,000",
        coordinator1: 'Vedant',
        coordinator2: 'Aishwarya',
        contact1: '+91 9136121168',
        contact2: '+91 9158525552',
    },
    {
        id: 2,
        title: "Refaktor",
        imgname: "refaktor.png",
        brief: "We present you our National Level Hackathon, REFAKTOR, a platform to put your imagination against th...",
        description: "We present you our National Level Hackathon, REFAKTOR, a platform to put your imagination against the young, ignited, and bright minds across the country, where you shall tackle some of the most pressing challenges while blending a culture of product innovation and a problem-solving mindset.",
        venue: "TPO Hall",
        date: "24-25th Feb",
        price: "Rs. 2,00,000",
        coordinator1: 'Amey ',
        coordinator2: 'Omkar ',
        contact1: '+91 8104635451',
        contact2: '+91 9930900866',
        price: '2,00,000',
    },
    {
        id: 3,
        title: "CoDefine",
        imgname: "co_define.png",
        brief: "Presenting CODEFINE, a thrilling event by Technovanza consisting of three tracks that require both s...",
        description: "Presenting CODEFINE, a thrilling event by Technovanza consisting of three tracks that require both skills and smart working ability. Participants are required to complete the task in the given time and produce a solution for their respective track that satisfies the theme.",
        venue: "DL003",
        date: "25th Feb",
        price: "Rs. 80,000",
        coordinator1: 'Sayali',
        coordinator2: 'Omkar',
        contact1: '+91 7021651484',
        contact2: '+91 9930900866',
    },
    {
        id: 4,
        title: "Smart City",
        imgname: "smartcity.png",
        brief: "Technovanza presents you an opportunity to put forward your thoughts on creating a smarter future fo...",
        description: "Technovanza presents you an opportunity to put forward your thoughts on creating a smarter future for the world through this event. The Smart City agenda entails improving the citizens' quality of life, strengthening and diversifying the economy while prioritizing environmental sustainability through adoption of smart solutions.",
        venue: "Study Space",
        date: "TBD",
        price: "Rs. 25,000",
        coordinator1: 'Parth',
        coordinator2: 'Janesh',
        contact1: '+91 9136173915',
        contact2: '+91 9969354247',
    },
    {
        id: 5,
        title: "Aqua",
        imgname: "aqua.png",
        brief: "VJTI Technovanza presents to you Aqua. Aqua is a waterborne event. The theme for this year is buildi...",
        description: "VJTI Technovanza presents to you Aqua. Aqua is a waterborne event. The theme for this year is building a dyson sphere around the sun.",
        venue: "Textile Garden",
        date: "TBD",
        price: "Rs. 15,000",
        coordinator1: 'Indrayani',
        coordinator2: 'Aryan',
        contact1: '+91 7385794714',
        contact2: '+91 9967968577',
    },
    {
        id: 6,
        title: "Escape Room",
        imgname: "escaperoom.jpg",
        brief: "In the world of cosmos, you and your team now have a chance to be astronauts and explore the univers...",
        description: "In the world of cosmos, you and your team now have a chance to be astronauts and explore the universe, which has been the dream since forever. Spaceship X69420 is now recruiting people interested in becoming an astronaut and gaining this wonderful experience wherein they will learn and explore space.",
        venue: "Al102 AL103",
        date: "TBD",
        price: "Rs. 10,000",
        coordinator1: 'Parth',
        coordinator2: 'Janesh',
        contact1: '+91 9136173915',
        contact2: '+91 9969354247',
    },
    {
        id: 7,
        title: "Robosoccer",
        brief: "The last few months belonged to our favourite sport, with our favourite players shining in the world cup. Now it is your turn to touch the grass with your bots...",
        description: "The last few months belonged to our favourite sport, with our favourite players shining in the world cup. Now it is your turn to touch the grass with your bots. The game will have 2 bots clashing. The arena will be divided into two halves, one half dedicated to the attacker bot, and other to the defender bot, each match will consist of two halves.",
        imgname: "robosoccer.png",
        date: "TBD",
        venue: "VJTI Quad",
        contact1: "+91 8928780890",
        contact2: "+91 9404494474",
        price: "Rs. 20,000",
        coordinator1: "Jay",
        coordinator2: "Arshad",
    },
    {
        id: 8,
        title: "Robostrike",
        brief: "TECHNOVANZA 2022-23 presents to you the most eccentric and enigmatic Robo event 'Robostrike'...",
        description: "TECHNOVANZA 2022-23 presents to you the most eccentric and enigmatic Robo event 'Robostrike'. The gameplay represents a blend of 'Air Hockey' and 'Robotics'. RoboStrike will have 2 bots going head to head, the gameplay will consist of 3 rounds.",
        imgname: "robostrike.png",
        date: "TBD",
        venue: "Outside COE",
        contact1: "+91 9768390828",
        contact2: "+91 8007703970",
        price: "Rs. 20,000",
        coordinator1: "Utkarsh",
        coordinator2: "Soham"
    },
    {
        id: 9,
        title: "Robosumo",
        brief: "ROBOSUMO, a battle of toughness, power, and sheer determination to withstand everything that comes in the way between your bots!..",
        description: "ROBOSUMO, a battle of toughness, power, and sheer determination to withstand everything that comes in the way between your bots!",
        imgname: "robosumo.png",
        date: "TBD",
        venue: "VJTI Quad",
        contact1: "+91 8928780890",
        contact2: "+91 9307956106",
        price: "Rs. 25,000",
        coordinator1: "Jay",
        coordinator2: "Farhan"
    }
    ,
    {
        id: 10,
        title: "Monster Arena",
        brief: "Monster arena brings you a fierce obstacle course that will test the strength of the bot and the will of the team...",
        description: "Monster arena brings you a fierce obstacle course that will test the strength of the bot and the will of the team crossing those obstacles together.",
        imgname: "monsterarena.png",
        date: "TBD",
        venue: "Textile Garden",
        contact1: "+91 9326738161",
        contact2: "+91 9833937107",
        price: "Rs. 20,000",
        coordinator1: "Purvesh",
        coordinator2: "Dhruv",
    }
    ,
    {
        id: 11,
        title: "Whodunnit",
        brief: "VJTI Technovanza calls upon all amateur detectives to solve a murder mystery. You and your team are on a quest...",
        description: "VJTI Technovanza calls upon all amateur detectives to solve a murder mystery. You and your team are on a quest to become the greatest detectives of all time. So, don your thinking hats and magnifying glasses, get your weapons ready as you wander through the hallways of the Hotel Nevermore to find 'Whodunnit?'",
        imgname: "whodunnit.png",
        date: "TBD",
        venue: "AL303",
        contact1: "+91 8280898464",
        contact2: "+91 9969354247",
        price: "Rs. 10,000",
        coordinator1: "Atharva",
        coordinator2: "Janesh"
      }
      ,
      {
        id: 12,
        title: "Technoquasar",
        brief: "TechnoQuasar is a software-oriented contest that will steer individuals to assess themselves in the field of computer science...",
        description: "TechnoQuasar is a software-oriented contest that will steer individuals to assess themselves in the field of computer science in general. It will be a 3 round event, with increasing difficulty in each round, and the final round being a DSA coding competition.",
        imgname: "technoquaser.png",
        date: "24th Feb",
        venue: "DL002",
        contact1: "+91 7021651484",
        contact2: "+91 8104635451",
        price: "Rs. 25,000",
        coordinator1: "Sayli",
        coordinator2: "Amey",
      }
      ,
      {
        id: 13,
        title: "Coding Surfers",
        brief: "Based on the concept of the popular mobile game Subway Surfers, “Coding Surfers” is a similar intense fun event...",
        description: "Based on the concept of the popular mobile game Subway Surfers, “Coding Surfers” is a similar intense fun event with pairs of contestants pit against each other. One plays the role of police while the other is a thief. The police must use his/her programming skills to get to the same position as the thief and catch him/her while the thief must use the same to escape the police.",
        imgname: "codingsurfers.png",
        date: "24th Feb",
        venue: "Mechanical Dept.",
        contact1: "+91 9930900866",
        contact2: "+91 8104635451",
        price: "Rs. 18,000",
        coordinator1: "Omkar",
        coordinator2: "Amey"
      }
      ,
      {
        id: 14,
        title: "Scigenix",
        brief: "Scigenix is an event for the students from class 8th to 12th along with students pursuing education towards Diploma courses...",
        description: "Scigenix is an event for the students from class 8th to 12th along with students pursuing education towards Diploma courses post 10th grade. It involves building a working prototype or model related to a particular theme. It consists of 3 rounds, with the final round being the presenting of the models.",
        imgname: "scigenix.png",
        date: "24th Feb",
        venue: "CL 301",
        contact1: "+91 9152709745",
        contact2: "+91 8104635451",
        price: "Rs. 10,000",
        coordinator1: "Shubham",
        coordinator2: "Amey"
      }
      ,
      {
        id: 15,
        title: "Checkpoint Hacker",
        brief: "Checkpoint Hacker is a fun coding event in which participants are handed over a maze with a few places marked on it as checkpoints...",
        description: "Checkpoint Hacker is a fun coding event in which participants are handed over a maze with a few places marked on it as checkpoints. The gameplay is to solve a few coding questions to pass through the checkpoints and complete the maze.",
        imgname: "checkhacker.png",
        date: "24th Feb",
        venue: "CL 101",
        contact1: "+91 9930900866",
        contact2: "+91 8104635451",
        price: "Rs. 10,000",
        coordinator1: "Omkar",
        coordinator2: "Amey"
      }
      ,
      {
        id: 16,
        title: "Escape the Catacombs",
        brief: "A number of billboards shall be placed across the VJTI College Campus during the Technovanza Festival...",
        description: "A number of billboards shall be placed across the VJTI College Campus during the Technovanza Festival, containing a mystery puzzle on them. Solving the mystery will require the participant to solve a question in the form of code snippet/syntax, a question-related to DSA(Data Structures & Algorithms), OOPs or any other computer science-related question at certain points within the mystery.",
        imgname: "etc.png",
        date: "24th Feb",
        venue: "Mechanical Building",
        contact1: "+91 8104635451",
        contact2: "+91 9930900866",
        price: "Rs. 10,000",
        coordinator1: "Amey",
        coordinator2: "Omkar"
      }
      ,
      {
        id: 17,
        title: "Gamer's Arena",
        brief: "GAMER'S ARENA - A Valorant tournament. If you are a gaming enthusiast who is eagerly waiting for an event like this, here is the opportunity...",
        description: "GAMER'S ARENA - A Valorant tournament. If you are a gaming enthusiast who is eagerly waiting for an event like this, here is the opportunity to contest your heart out",
        imgname: "gamersarena.png",
        date: "24th-25th Feb",
        venue: "VJTI Campus",
        contact1: "+91 8452819428",
        contact2: "+91 9372958228",
        price: "Rs. 20,000",
        coordinator1: "Yutika Shetty",
        coordinator2: "Ninad Jadhav"
      }
      

]

export default eventsData;